package family.project.domain.enums;

public enum BoardTag {
    DOMESTIC,
    OVERSEAS,
    TRAVEL_REVIEW,
    TRAVEL_TIPS,
    PREGNANCY_CHILDBIRTH,
    INFANT_CARE_PARENTING,
    PARENTING_PRODUCT_REVIEW,
    PARENTING_TIPS,
    FOOD_RECOMMENDATIONS_REVIEWS,
    RESTAURANTS_BY_REGION,
    SHARE_COOKING_RECIPES


}
