spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family_db?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  profiles:
    active: local

  messages:
    basename: messages, errors

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect

# logging
logging:
  level:
    org:
      hibernate:
        SQL: debug

file:
  dir: C:/projectimg/